# Generated by Django 4.1.7 on 2023-03-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.IntegerField()),
                ('citizen_id', models.IntegerField()),
                ('town', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('building', models.CharField(max_length=256)),
                ('apartment', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('relatives', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('citizens', models.ManyToManyField(to='main.citizen')),
            ],
        ),
        migrations.AddConstraint(
            model_name='citizen',
            constraint=models.UniqueConstraint(fields=('import_id', 'citizen_id'), name='unique_import_citizen_combination'),
        ),
    ]
